# Generated by Django 5.1.7 on 2025-05-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('children', 'Children'), ('unisex', 'Unisex')], max_length=20),
        ),
    ]
