# Generated by Django 5.1.7 on 2025-05-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_type',
            new_name='category',
        ),
    ]
