# Generated by Django 5.1.7 on 2025-06-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_note_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
