# Generated by Django 5.1.7 on 2025-06-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
