# Generated by Django 5.1.7 on 2025-06-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='logo',
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.vendor'),
        ),
    ]
