# Generated by Django 5.1.7 on 2025-06-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_joined_at_vendor_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='store_name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='created_at',
            new_name='joined_at',
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_logos/'),
        ),
    ]
