# Generated by Django 5.1.7 on 2025-06-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
