# Generated by Django 5.1.7 on 2025-06-11 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_product_pieces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='amount',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
