# Generated by Django 5.1.3 on 2025-06-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_amount_sale_total_price_remove_sale_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=50, null=True),
        ),
    ]
