# Generated by Django 5.1.3 on 2025-06-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='sale',
            name='buyer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
