# Generated by Django 5.1.3 on 2025-06-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='buyer',
            new_name='name',
        ),
    ]
