# Generated by Django 5.1.3 on 2025-06-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_sale_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
