# Generated by Django 5.1.7 on 2025-06-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_orderitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pieces',
            new_name='quantity',
        ),
    ]
