# Generated by Django 5.1.7 on 2025-06-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_order_items_remove_order_status_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Paid & Picked', 'Paid & Picked')], default='pending', max_length=20),
        ),
    ]
