# Generated by Django 5.1.7 on 2025-06-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_remove_order_product_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
