# Generated by Django 5.1.7 on 2025-06-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid & picked', 'Paid & Picked')], default='Pending', max_length=50, null=True),
        ),
    ]
