# Generated by Django 5.1.7 on 2025-06-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='order',
        ),
    ]
