# Generated by Django 5.1.7 on 2025-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_sale_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='buyer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
