# Generated by Django 5.1.7 on 2025-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_sale_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
